export const GET_INSTITUTION = "GET_INSTITUTION";
export const GET_ONE_INSTITUTION = "GET_INSTITUTION";
export const LOAD_INSTITUTION = "LOAD_INSTITUTION";
export const FAIL_INSTITUTION = "FAIL_INSTITUTION";
